variables:
    GIT_STRATEGY: clone
#The following job performs the unit tests.
unit_tests:
  script:
#we use the --sitepackages option so that tox use the packages available
#globally. We copy the mounted volume to /tmp in order to avoid the creation
#of files with different permissions that could not be deleted by the
#gitlab-ci-runner in the next run.
    - "docker run -v $(pwd):/data -w /data devenv-tessia_baselib:1.0 sh -c 'cp -r /data /tmp; cd /tmp/data; tox -v --sitepackages -e test'"
