variables:
  GIT_STRATEGY: clone

stages:
  - prepare
  - unit_tests
  - pylint

# First build a docker image with the checked-out sources from a previously built
# base image with all the requirements installed. Having these two images is a
# temporary solution until the dev server has access to pip and the requirements
# can be installed every time.
prepare:
  stage: prepare
  script:
    - docker build -f tools/ci/Dockerfile-tessia_baselib-testenv -t tessia_baselib-testenv:latest --no-cache .

unit_tests:
  stage: unit_tests
  script:
    - docker run tessia_baselib-testenv:latest tools/run_tests.py

pylint:
  stage: pylint
  script:
    - docker run tessia_baselib-testenv:latest tools/run_pylint.py
  # For now allow failed pylints, remove this in the future to
  # enforce perfect linting.
  allow_failure: true
