# directory where doc files are located
docs_dir: doc
# where to store output files
site_dir: build/html
# enable permalinks for each header
markdown_extensions:
    - toc:
        permalink: True
# css/html theme
theme: readthedocs
site_name: Tessia base library
repo_url: https://gitlab.com/tessia-project/tessia-baselib
copyright: Copyright IBM Corp. 2016, 2017
pages:
- Home: 'index.md'
- Users:
    - How to install: 'users/install.md'
    - Live image to enable HMC netboot: 'users/live_image.md'
    - Hypervisors API: 'users/api_hypervisors.md'
    - Guests API: 'users/api_guests.md'
    - Hypervisor HMC: 'users/hypervisor_hmc.md'
    - Hypervisor KVM: 'users/hypervisor_kvm.md'
- Developers:
    - How to contribute (development process): 'developers/contributing.md'
    - Coding guidelines: 'developers/coding_guidelines.md'
    - How to setup a development environment: 'developers/dev_env.md'
    - Tests: 'developers/tests.md'
    - Working with documentation: 'developers/documentation.md'
    - Validation of parameters with json schemas: 'developers/params_validation.md'
