# directory where doc files are located
docs_dir: .
# where to store output files
site_dir: ../build/html
site_favicon: img/favicon.ico
# enable permalinks for each header
markdown_extensions:
    - toc:
        permalink: True
# css/html theme
theme: cosmo
site_name: tessia-baselib
repo_url: https://gitlab.com/tessia-project/tessia_baselib
#copyright: TBD
pages:
- Home: 'index.md'
- User guide:
    - Build and install: 'users/build.md'
    - Hypervisor HMC: 'users/hypervisor_hmc.md'
    - Hypervisor KVM: 'users/hypervisor_kvm.md'
    - REST-API: 'users/api.md'
- Developers:
    - Coding guidelines: 'developers/coding_guidelines.md'
    - Development process: 'developers/dev_process.md'
    - Unit tests: 'developers/unit_tests.md'
    - Working with documentation: 'developers/documentation.md'
    - Validation of parameters with json schemas: 'developers/params_validation.md'
